name: auth_repository
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http_handler:
    path: ../http_handler
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  very_good_analysis: ^3.0.1
