name: weappear
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  appsize: ^1.2.0
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.0.3
  data_persistence:
    path: packages/data_persistence
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  http_handler:
    path: packages/http_handler
  weappear_localizations:
    path: packages/weappear_localizations
  weappear_ui:
    path: packages/weappear_ui


dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/logo.png
