name: weappear
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  appsize: ^1.2.1
  bloc: ^8.0.3
  client:
    path: packages/client
  data_persistence:
    path: packages/data_persistence
  dots_indicator: ^2.1.0
  equatable: ^2.0.3
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  go_router: ^5.2.1
  go_router_flow: ^5.2.0
  http_handler:
    path: packages/http_handler
  introduction_screen: ^3.0.2
  weappear_localizations:
    path: packages/weappear_localizations
  weappear_ui:
    path: packages/weappear_ui

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/product-sans/Product_Sans_Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/product-sans/Product_Sans_Bold_Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/product-sans/Product_Sans_Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/product-sans/Product_Sans_Italic.ttf
          weight: 400
          style: italic
