name: weappear_ui
description: A package that contains reusable components for the WeAppear apps.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  auto_size_text: ^3.0.0
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_password_strength: ^0.1.6
  flutter_svg: ^1.0.3
  matcher: ^0.12.11
  rive: ^0.8.1
  shimmer: ^2.0.0

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Gravity
      fonts:
        - asset: fonts/gravity/Gravity-UltraLight.otf
          weight: 100
          style: normal
        - asset: fonts/gravity/Gravity-UltraLightItalic.otf
          weight: 100
          style: italic
        - asset: fonts/gravity/Gravity-Light.otf
          weight: 200
          style: normal
        - asset: fonts/gravity/Gravity-LightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/gravity/Gravity-Book.otf
          weight: 300
          style: normal
        - asset: fonts/gravity/Gravity-BookItalic.otf
          weight: 300
          style: italic
        - asset: fonts/gravity/Gravity-Regular.otf
          weight: 400
          style: normal
        - asset: fonts/gravity/Gravity-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/gravity/Gravity-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/gravity/Gravity-Bold.otf
          weight: 700
