name: weappear_ui
description: A package that contains reusable components for the WeAppear apps.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  another_flushbar: ^1.10.28
  appsize: ^1.2.0
  auto_size_text: ^3.0.0
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_password_strength: ^0.1.6
  flutter_svg: ^1.0.3
  matcher: ^0.12.11
  rive: ^0.8.1
  shimmer: ^2.0.0
  weappear_localizations:
    path: ../weappear_localizations

dev_dependencies:
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
