name: data_persistence
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  very_good_analysis: ^2.4.0

dependencies:
  hive: ^2.0.5
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
  generate: true
